### PR TITLE
Migrate scrolling magic and form validation

### LINKED ISSUE #54: Used contact form validation library does not support new TLDs
Switch to another validation library. Maybe after moving to the latest bootstrap version.

Relevant issue:
https://github.com/ReactiveRaven/jqBootstrapValidation/issues/185

### PR DESCRIPTION
**Pull request by stp-ip**
Fixes #54

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
This is fantastic. Thanks again for your great work!

I merged this PR as 975478bf8ceecd7445743194bcbf29d3a59ba68e and used [`.Site.Params.email`](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/layouts/partials/contact.html#L73) instead of `.Site.Params.contact.email` in warning.

**Comment by digitalcraftsman** [comment]
I guess this issue also fixes #54, right?

**Comment by stp-ip** [comment]
The email setting was migrated to .Site.Params.contact.email to make the config more consistent.
See:
https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/exampleSite/config.toml#L264

**Comment by digitalcraftsman** [comment]
You're right - I totally forgot to update the example config file that I use for my testing environment.

**Comment by stp-ip** [comment]
Nevermind. Now it's compatible and works \o/

**Pull request closed without merging**
