### PR TITLE
Add possibility to disable fonts

### PR DESCRIPTION
**Pull request by stp-ip**
Reduce reliance on external fonts.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Thank you for the addition.

**Comment by stp-ip** [comment]
Thanks awesome for the fast merge. If this is something you would like to see more, I'll contribute some more options such as piwik or disabling google analytics. (Already in production, but didn't upstream yet.)

**Comment by digitalcraftsman** [comment]
> Thanks awesome for the fast merge. If this is something you would see more, I'll contribute some more options such as piwik or disabling google analytics. (Already in production, but didn't upstream yet.)

I appreciate any contributions that make the theme more customizable. This theme uses the internal Google Analytics template that is shipped with Hugo. If you don't assign anything to the [`googleAnalytics`](https://github.com/digitalcraftsman/hugo-agency-theme/blob/master/exampleSite/config.toml#L7) then the tracking snippet wont be included.

**Comment by stp-ip** [comment]
Awesome. I think the googleAnalytics change maybe in another theme. Will upstream my changes. I appreciate it.

**Pull request merged**
