### PR TITLE
[WIP] Breaking change! Restructure into multiple files and multilingual

### LINKED ISSUE #75: fix oddly asymmetric layout of team
this looks weird to me because it is not centered. Feels like there should be 3 per row perhaps?

assymetric

oddly, upstream at https://blackrockdigital.github.io/startbootstrap-agency/ the layout IS symmetric with 3 per row:

symmetric

### PR DESCRIPTION
**Pull request by stp-ip**
Also fixed a few bugs and added additional features.

Will test it in the coming days and hopefully finish documentation and maybe a few other features.

Tested it quite a bit and actually ported my own website over and it's running in production for the last few hours.

Would be great, if someone else could take a look either with their page being migrated or with the example site.

Will see what other features I can push in and if it makes sense to reorganize the commits.

Fixes: #75 #79 #72 #71 #67 #62 #61 #49 #41

### CODE REVIEW

**Comment by stp-ip** [comment]
Seems like most of it is working fine. Last issue seems to be that the contact form via postURL and captcha enabled can still be circumvented. Have to look into that more deeply.

Everything else is open for testing and feedback. Will most likely port another few sites to this new version during the weeks and see, what comes up.

**Comment by digitalcraftsman** [comment]
Hi Michael,

thanks again for your ongoing contributions to this theme. Please excuse the late response. During my busy exam phase I've glanced over your pull request but forgot to track it further since it doesn't appear in the notification center anymore.

Nonetheless, it's great to see all the new features / improvements, especially the integration of i18n. While checkout out your additions (and making some changes on my own) I compiled this list of questions / notes:

- currently there are two example config files. Would you like to get them merged or do your prefer them being separate?
- the projects in the portfolio section can't be opened in modals anymore? I don't think this is intended as the yaml files for the projects are still there
- with the removal of the logo it looks a bit odd if the main menu with a few links is completely aligned to the right. Do you prefer the current state or the menu being centered?
- Currently, the page "Rechtliches" appears in the main menu when using `config.toml` next all the menu items in English. However, when using `config-multilingual.toml` Hugo distinguishes between German and English menu items. In conclusion, Hugo seems to add all menu items added to a menu if no other language was defined in the config file. To avoid this and to reduce the maintenance overhead from the first bullet I would merge both config files. What do you think?

**Comment by stp-ip** [comment]
> thanks again for your ongoing contributions to this theme. Please excuse the late response. During my busy exam phase I've glanced over your pull request but forgot to track it further since it doesn't appear in the notification center anymore.

No worries due to the nature of basically rewriting most of the theme and now also switching to bootstrap 4. I think it might be better to release this new iteration as a new theme. Work is ongoing at github.com/okkur/syna
When that is finished, we might use an intermediate iteration, the multi language improvements and other non-breaking changes should still be merged here I feel.
What do you think about this. Makes the breaking changes much easier to handle and easier for users to grasp.

> Nonetheless, it's great to see all the new features / improvements, especially the integration of i18n. While checkout out your additions (and making some changes on my own) I compiled this list of questions / notes:
>
>     currently there are two example config files. Would you like to get them merged or do your prefer them being separate?

Currently there are 2 config files one for multi language and one for single language. We might wanna simplify into one file, depending on what we decide above.

>     the projects in the portfolio section can't be opened in modals anymore? I don't think this is intended as the yaml files for the projects are still there

That seems like unintentional.

>     with the removal of the logo it looks a bit odd if the main menu with a few links is completely aligned to the right. Do you prefer the current state or the menu being centered?

I was just going with the agency default, which was right aligned afaik.

>     Currently, the page "Rechtliches" appears in the main menu when using config.toml next all the menu items in English. However, when using config-multilingual.toml Hugo distinguishes between German and English menu items. In conclusion, Hugo seems to add all menu items added to a menu if no other language was defined in the config file. To avoid this and to reduce the maintenance overhead from the first bullet I would merge both config files. What do you think?

First let's decide on the first and then we can merge the two files. The issue I had with one file was that the menu didn't seem to work, when using the multi language configuration, but only using one language.

**Comment by stp-ip** [comment]
So my suggestion would be new theme (syna) for bs4 + rewrite + multi file based.
And use some of the cleanup to introduce backwards compatible features such as single page, multilingual to agency. This would mean we don't break people and have 2 good bases to keep on developing.

**Comment by digitalcraftsman** [comment]
> No worries due to the nature of basically rewriting most of the theme and now also switching to bootstrap 4. I think it might be better to release this new iteration as a new theme. Work is ongoing at github.com/okkur/syna

This looks exiting!

> When that is finished, we might use an intermediate iteration, the multi language improvements and other non-breaking changes should still be merged here I feel.
What do you think about this. Makes the breaking changes much easier to handle and easier for users to grasp.

Most of the major-changes are indeed breaking ones and would add more hassle to the users. In the midterm it makes sense to merge only the none-breaking changes to get the best of both worlds.

Rewriting the whole theme in Bootstrap 4 also seems more future-proof. From the longterm perspective I could image that your theme becomes the successor of this one, an agency 2.0 theme if you like.

This way users can decide whether they stick with this theme or take the extra mile to get the new (backwards-incompatible) features.

**Comment by stp-ip** [comment]
Great. I'll see when I am able to finish the first iteration of Syna and already backport some of the non-breaking ideas into agency. Most likely doing that via separate pull requests. Will take the suggestions you committed into account. Always nice to see different ways to use hugo.

**Comment by stp-ip** [comment]
Just a small update.
Unstable draft is ready for a first review. Feedback welcome.
Will try to work more on it this week and see how far it can get.

full-v0 1 0

**Comment by digitalcraftsman** [comment]
This looks very good. Your repo was already on my radar :wink:

**Comment by stp-ip** [comment]
Demo page: https://syna-demo.okkur.io

**Pull request closed without merging**
