### PR TITLE
Add 404 page + some minimal cleanups

### PR DESCRIPTION
**Pull request by stp-ip**

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Thank you for this further additions. I had a look at the 404 page and I think the page will not be recognized as a 404 page because the hero is the same as on the homepage. The section that says "Page couldn't be found"  is only visible after scrolling.

Couldn't we reuse the hero section? By adding a CSS rule we could define that this section should take the whole width and height of the screen. If I'm correct this could be easily done with the `vh` and `vw` units (viewport height/width) in CSS.

**Comment by stp-ip** [comment]
Will look into reusing the hero page.

**Comment by stp-ip** [comment]
Simplified the 404 page to reused the hero element and strip everything except footer and nav.

Hope this makes the site clearer.

Additionally got some changes in for jquery.

**Comment by digitalcraftsman** [comment]
The 404 page looks awesome :+1:

**Pull request merged**
